
services:
        web:
                image: hunger
                build: .
                env_file:
                        - .env # This file is optional; defaults will be used if it does not exist
                ports:
                        - "8288:8288"
                volumes:
                        - ./instance:/instance
                restart: unless-stopped
